# Generated by Django 4.2.20 on 2025-05-16 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projects",
            name="images",
        ),
        migrations.RemoveField(
            model_name="projects",
            name="project_banner_image",
        ),
    ]
