# Generated by Django 4.2.20 on 2025-05-11 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogpost",
            options={"verbose_name_plural": "Blog Posts"},
        ),
        migrations.AlterModelOptions(
            name="projects",
            options={"verbose_name_plural": "Projects"},
        ),
        migrations.AlterModelOptions(
            name="skills",
            options={"verbose_name_plural": "Skills"},
        ),
        migrations.AddField(
            model_name="projects",
            name="slug",
            field=models.SlugField(default="testing-slug", max_length=8, unique=True),
            preserve_default=False,
        ),
    ]
