# Generated by Django 4.2.20 on 2025-05-13 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_blogpost_options_alter_projects_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="projects",
            old_name="link",
            new_name="github_link",
        ),
        migrations.AddField(
            model_name="projects",
            name="deployed_link",
            field=models.URLField(default="http://test.com"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="projects",
            name="slug",
            field=models.SlugField(
                blank=True, editable=False, max_length=8, unique=True
            ),
        ),
    ]
