# Generated by Django 4.2.20 on 2025-05-14 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_rename_link_projects_github_link_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projects",
            name="project_readme",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="projects",
            name="project_images",
            field=models.ImageField(blank=True, null=True, upload_to="project_images/"),
        ),
    ]
