# Generated by Django 4.2.20 on 2025-05-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_projects_project_readme_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projects",
            name="project_images",
        ),
        migrations.AddField(
            model_name="projects",
            name="images",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
