# Generated by Django 4.2.20 on 2025-05-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_remove_projects_project_images_projects_images"),
    ]

    operations = [
        migrations.AddField(
            model_name="projects",
            name="github_raw_content_base_url",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
