# Generated by Django 4.2.20 on 2025-05-14 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_projects_github_raw_content_base_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projects",
            name="images",
            field=models.ImageField(blank=True, null=True, upload_to="project_images/"),
        ),
        migrations.AlterField(
            model_name="projects",
            name="slug",
            field=models.SlugField(
                blank=True, editable=False, max_length=100, unique=True
            ),
        ),
    ]
