# Generated by Django 4.2.20 on 2025-05-14 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_alter_projects_images_alter_projects_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projects",
            name="slug",
            field=models.SlugField(
                blank=True, editable=False, max_length=8, unique=True
            ),
        ),
    ]
