# Generated by Django 4.2.20 on 2025-05-14 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_update_slug_field_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projects",
            name="slug",
            field=models.SlugField(
                blank=True, editable=False, max_length=100, unique=True
            ),
        ),
    ]
